version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root1234
      MONGO_INITDB_DATABASE: test
    volumes:
      - mongo-data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "9000:9000"
    environment:
      - DB_URI=mongodb://root:root1234@mongodb:27017/test?authSource=admin
    depends_on:
      - mongodb
    volumes:
      - ./server:/app

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:9000
    depends_on:
      - backend
    volumes:
      - ./client:/app
    command: ["npm", "start"]

volumes:
  mongo-data: